### ISSUE TITLE
ItemsModel の Item クラスについて

### ISSUE THREAD

**Issue by hayabusabusa** [secretused/MentaSecondTestApp#1]
## 📝 詳細

`Item` というクラスがありますが、
こちら API のレスポンスもしくはデータベースに格納するデータを表すクラスであっていますか？

もしそうならクラスではなく、構造体で定義すべきです。
API のレスポンスのようなデータのプロパティはアプリ側から変更することはなく、
構造体であればただのデータの塊であることを明示することができます。

また、構造体で定義することでイニシャライザが自動で生成されます。

```Swift
struct Item: Codable {
    // var ではなく、let で定数にする
    let name: String
    let date: String 

    // init は自動で作られるので、定義する必要がない
}

// 利用例
Item(name: "Name", date: "2020-01-01")
```

ただし、Realm のような DB を利用する場合はクラスで定義する必要があるので、
Realm を利用する場合は少し注意してください。

**Comment by yutaToba1008** [comment]
API のレスポンスを格納するクラスです。
そうですね、Modelは基本構造体の方が良いですね。
今後Realmを使用してController等のデータを保存したいのですが、その場合ModelもClassにする必要がありますか？
依存関係が曖昧なので教えて欲しいです。

**Comment by hayabusabusa** [comment]
@secretused 
Realm を使用するなら API のレスポンスデータを Realm の `Object` を継承した**クラス**にする必要がありますね。
イメージとしては以下のような感じです。

```Swift
import RealmSwift

class Item: Object, Decodable {
    // ...
}
```

**本当に最低限の DB**で良いなら `UserDefaults` を利用する方法もあります。
`UserDefaults` は `Data` 型を保存できるので、`Item` 構造体を `Codable` に準拠させて `JSONEncoder` で `Data` に変換してしまえば保存が可能です。( [参考](https://qiita.com/SatoTakeshiX/items/b108e5ee0656f88d117b) )

あと今更ですが `Item` という構造体名ももう少し詳細にするべきかもしれないです。
もしこの構造体が映画の情報を表すものならば、例えば `MovieItem` など `Movie` などですね。

**Comment by yutaToba1008** [comment]
Realmも初めて使用するのでRegisterControllerから受け取ったデータをListViewControllerに保存したいと思っております。

**Comment by hayabusabusa** [comment]
@secretused 
なるほど、ではクラスにした方がいいかもしれませんね。
Realm のオブジェクトにはマネージドオブジェクト、アンマネージドオブジェクトという考え方があるので、
その辺りに気を付ければ問題なく使えると思います。( [参考](https://qiita.com/nomunomu0504/items/3cf2fcb0067b6397aab9#%E3%83%A2%E3%83%87%E3%83%AB%E3%82%AA%E3%83%96%E3%82%B8%E3%82%A7%E3%82%AF%E3%83%88%E6%9B%B4%E6%96%B0%E6%99%82%E3%81%AE%E8%A8%AD%E5%AE%9A) )

**Comment by yutaToba1008** [comment]
Modelを作りdynamic変数を作ると思うのですが、自分の場合Realmに保存したいのはAPIで取り出した全データではなく、
RegisterViewControllerで保存したデータを保存したいためモデルクラスの作成はどうしたら良いのでしょうか？
またRegisterViewController / addListTapped時にrealm.add()をすると思うのですが、Singletonとの兼ね合いはどうすればよいのでしょうか？Singletonと保存は別物と言われたのでできると思うのですが。

**Comment by hayabusabusa** [comment]
@secretused 
> 自分の場合Realmに保存したいのはAPIで取り出した全データではなく、
RegisterViewControllerで保存したデータを保存したいためモデルクラスの作成はどうしたら良いのでしょうか？

それならば API から受け取ったデータと保存するデータを分けてしまえばいいと思います。
API から受け取ったデータは構造体で作成し、保存は Realm の `Object` クラスを継承したクラスで行うようなイメージです。

この方法の場合、Realm に保存する前に API から受け取ったデータを保存するクラスに変換する必要がありますね。

```Swift
// API からのレスポンスを表すデータ
struct Movie: Decodable {
    let name: String
}

// Realm に保存するデータ
class RegisteredMovie: Object {
    @objc dynamic var name: String = ""
}

// 保存の際に変換が必要
var registeredMovie = RegisteredMovie()
registeredMovie.name = movie.name

// Realm に保存
let realm = try! Realm()

try! realm.write {
    realm.add(registeredMovie)
}
```

こちらの方が変換の一手間が加わりますが、API のレスポンスと保存したデータを明確に分けることができるのがメリットになると思います。

**Comment by yutaToba1008** [comment]
`// Realm に保存するデータ
class RegisteredMovie: Object {
    @objc dynamic var name: String = ""
}`
こちらはItemModelで宣言するということですか？

**Comment by hayabusabusa** [comment]
@secretused 
いいえ、別のファイルで定義した方がいいと思います。
どちらもデータの集まりを定義したものなので、ファイル名と構造体名、クラス名を合わせて作った方が良いと思います。

```Swift
// Movie.swift

struct Movie: Decodable {
    let name: String
    // ...
}
```

```Swift
// RegisteredMovie.swift

class RegisteredMovie: Object {
    @objc dynamic var name: String = ""
    // ...
}
```

**Comment by yutaToba1008** [comment]
class ListAddedData{
    static let shared = ListAddedData()

    private init(){}

    private(set) var allList:[MovieItem] = []
    private(set) var selectedList:[MovieItem] = []
    
    func add(_ item:MovieItem, isSelected: Bool = false){
        allList.append(item)
        if isSelected{
            selectedList.append(item)
        }
    }}
--------------------------------------------------------------
    
        @objc func addListTapped(_ sender: UIBarButtonItem){
        
        //Optional<Item>
        guard let item = item else{
            print("item is nill")
            return
        }
        ListAddedData.shared.add(item, isSelected: false)
    }
--------------------------------------------------------------
上記のようにListViewControllerに情報を格納しているんですが、
先ほどの変換して保存やrealm.writeをSingletonのListAddedData.shared.add(item, isSelected: false)と宣言する場所？が同じだと
思っているのですが、この二つは何をそれぞれ行っていて、どのように書けばデータを受け取り保存できるのでしょうか？

**Comment by yutaToba1008** [comment]
**補足**　
allListが追加されたTableView(Segment[0])
selectedListはallListをスワイプして削除or移動の移動をした場合に追加されます。
なので基本的にはallListに受け取ったデータを格納しています。

**Comment by hayabusabusa** [comment]
@secretused 
> この二つは何をそれぞれ行っていて

すみません、「この二つ」というのは `Movie` 構造体と `RegisteredMovie` のことで合っていますか？

**Comment by yutaToba1008** [comment]
言葉足らずですみません。

ListViewControllerの
`func add(_ item:MovieItem, isSelected: Bool = false){
    allList.append(item)
    if isSelected{
        selectedList.append(item)
    }
}`

Realmの保存の仕方
`try! realm.write {
    realm.add(registeredMovie)
}`

この二つが同じデータを扱っている気がするのですが
allListに格納するデータとRealmに保存するデータ(Registerで選択され登録されたデータ)
RegisterViewControllerでaddListTapped時にRealmにSingletonデータListAddedData.sharedを保存するということでしょうか？

理解が難しい説明をしてすみません。
頭の中でイメージができないので言語化も難しいので、説明の質問を追記してください。

**Comment by hayabusabusa** [comment]
@secretused 
こちらこそ複雑になってしまい申し訳ないです。

> この二つが同じデータを扱っている気がするのですが

はい、おっしゃる通りで両方とも**中身は**同じデータです。

Realm は保存するオブジェクトを `Object` クラスを継承したクラスとして作成しなければいけないので、
API のレスポンスとは別でこのように2種類作成しました。

>  `allList`  に格納するデータと Realm に保存するデータ( Registerで選択され登録されたデータ )を
`RegisterViewController` で `addListTapped()` 時に Realm に Singleton のデータ `ListAddedData.shared` を保存するということでしょうか？

すみません、上記について完全に理解できていないので、少し確認させていただきたいのですが...

シングルトンには現在 **全てのリストのデータ** と **選択されたリストのデータ** の二つが管理されていて、
このうち **全てのリストのデータ** は API から受け取ったデータになり、**選択されたリストのデータ** は Realm に保存したいデータということで合っていますか？

**Comment by yutaToba1008** [comment]
返信が遅くなってしまいすみません。

> 全てのリストのデータ は API から受け取ったデータ

全てのデータは　Model化したMovieitemに入れて、ViewControllerのTableViewに表示してます。
ViewControllerでdidselectされたものをがRegisterViewControllerに渡しています(登録する)。そして
ListViewControllerのallListにRegisterViewControllerで保存したものを表示するTableViewになっています。

> シングルトンには現在 全てのリストのデータ と 選択されたリストのデータ の二つが管理されていて

シングルトンにはAPIから受け取ったデータの中から選んだ(登録した)データが入っています。
(上記のRegisterViewControllerで登録したもの)
ちなみにこちらがRealmで保存したいデータとなります。
つまりRegisterViewControllerで登録したものをSingletonでallListに渡してなおかつallListにRealmを使って保存したいです。

参考までにMain.storyboardの画像を載せますね。
![スクリーンショット 2020-09-02 0 49 25](https://user-images.githubusercontent.com/67790604/91875196-1e9c8a80-ecb6-11ea-815a-ba89112ac123.png)

**Comment by hayabusabusa** [comment]
@secretused 
なるほど！理解することができました🙇‍♂️

> 全てのデータは　Model化したMovieitemに入れて、ViewControllerのTableViewに表示してます。

こちらについて少し気になったのですが、**Model化** というのは MVC における **Model** ではなく、
API のレスポンスを表す**モデルオブジェクト**という意味であっていますか？

> シングルトンにはAPIから受け取ったデータの中から選んだ(登録した)データが入っています。

詳しくありがとうございます🙇‍♂️
`allList` がそもそも選択されたデータであり、Realm に保存したいデータだったんですね。

そうであれば、シングルトンは**データを保存するため**に使われていることになるので、
データの保存を Realm に任せてしまう場合はシングルトンは必要なくなりますね。
動作としては以下のようになると思います。

- **ViewController** で表示されているデータを選択
- **RegisterViewController** で登録( `addListTapped` を実行 )
- `addListTapped` 内で API のレスポンスから Realm のオブジェクトに変換して Realm に保存
- **ListViewController** の `viewWillAppear` で画面表示前に Realm から保存したデータを読み込み

上記のようにライフサイクルメソッドを使うことで無理にシングルトンを使用する必要はなくなります。

**Comment by yutaToba1008** [comment]
> API のレスポンスを表すモデルオブジェクトという意味

こちらが正しいです。

> addListTapped 内で API のレスポンスから Realm のオブジェクトに変換して Realm に保存

こちらは
`// 保存の際に変換が必要
var registeredMovie = RegisteredMovie()
registeredMovie.name = movie.name
`
この作業ということですか？
もしそうなら動作の流れは間違い無いです。

> データの保存を Realm に任せてしまう場合はシングルトンは必要なくなりますね。

やはりそうなのですね。
Singletonを使用する前はUserDefaultsで保存しようと思っていたのですが、遷移はしたくないのでと話したらSingletonか
`userDefault や Realm などのデータ永続化を利用する方法など色々ありそうに感じますが、いずれにせよ複数の View でデータを共有するのであれば、一度設計を見直した方がいいかもしれません。`
とのことでした。
安易にUserDefaultsを使用してはいけないと言われたのでSingletonを採用しましたが、最初からRealmで保存すればよかったのですね。

その場合Realmの使い方を知っていれば問題なさそうですね。
とりあえず保存を一回自分でやれるところまでやってまみます。

**Comment by yutaToba1008** [comment]
質問ですがデザインパターンでSingletonは一番使う？簡単とみましたが
Singletonはどのような場面で使うのですか？

**Comment by hayabusabusa** [comment]
@secretused 

> こちらは
// 保存の際に変換が必要 var registeredMovie = RegisteredMovie() registeredMovie.name = movie.name
この作業ということですか？
もしそうなら動作の流れは間違い無いです

はい、その処理のことです。

> Singletonを使用する前はUserDefaultsで保存しようと思っていたのですが、遷移はしたくないのでと話したらSingletonか
userDefault や Realm などのデータ永続化を利用する方法など色々ありそうに感じますが、いずれにせよ複数の View でデータを共有するのであれば、一度設計を見直した方がいいかもしれません。
とのことでした。
安易にUserDefaultsを使用してはいけないと言われたのでSingletonを採用しましたが...

なるほど、そうだったんですね。
`UserDefaults` は保存できるデータのサイズに上限があったり、`plist` 形式になっているためアプリ開発者以外でも簡単に中を覗けてしまうという点から安易に使うべきではないということを仰ったのかもしれませんね。

また、シングルトンは便利ですが、複数の箇所でデータのやりとりするための**データを保存する場所**として使ってしまうと
データの流れ( どこで追加されて、どこで読み込みが行われるのか )が掴みづらくなってしまいます。
そもそもアプリを一度落とした時点でシングルトンはメモリから解放されてしまうので、シングルトンで管理していたデータは消えてしまいますよね。

その辺りを Realm に任せて、きちんと設計( 例えば MVC など )して DB への保存のようなビジネスロジックを分離させることでより読みやすくなると思います。

> 質問ですがデザインパターンでSingletonは一番使う？簡単とみましたが
Singletonはどのような場面で使うのですか？

シングルトンについての詳しい解説は有名な [iOS エンジニアの方の記事](https://medium.com/swift-column/singleton-398078bcc58d)が参考になります。

シングルトンは個人的には**インスタンスが一つで良いもの**に使用するイメージです。

例えば API との通信( 複数のエンドポイントに GET や POST のリクエストを送る )を行う APIClient というクラスを作成したとします。このクラスはあくまで**通信の処理のみ**が実装されていて、何か変数を保持するものではないため、アプリ上で 1 つインスタンスが存在すれば良い存在になります。なので APIClient クラスをシングルトンにするという感じです。

余談ですが、`UserDefaults` はシングルトンパターンで作成されています😎

```Swift
let flag = true

// `standard` というのが `shared` にあたります.
UserDefaults.standard.set(flag, forKey: "flagKey")
```

**Comment by yutaToba1008** [comment]
詳しい説明やリンクの記載ありがとうございます。

> 設計( 例えば MVC など )して DB への保存のようなビジネスロジックを分離させること

設計に関してなのですがとりあえずRealmで保存ができてから考えればよろしいのでしょうか？
(色々とコードの変更があるとは思いますが)
この契約内では予想では追いつかないと思うのでiOS設計パターンを読んでみてまた概要を理解してから再契約するとは
思いますがどうでしょうか？

**Comment by hayabusabusa** [comment]
@secretused 
> 設計に関してなのですがとりあえずRealmで保存ができてから考えればよろしいのでしょうか？

そうですね。まずは Realm の導入、保存を実装してからの方が良いと思います。
Realm に関してもサポートできるので、不明な点はご質問いただいても大丈夫です🙇‍♂️

> この契約内では予想では追いつかないと思うのでiOS設計パターンを読んでみてまた概要を理解してから再契約するとは
思いますがどうでしょうか？

はい。それでも問題ありません👍
むしろ今回指摘させていただいたことを整理、もしくは実際にコードに反映させてみてからの方が良いと思います。

**Comment by yutaToba1008** [comment]
分かりました！
ありがとうございます😊
