### ISSUE TITLE
ListAddedData シングルトンについて

### ISSUE THREAD

**Issue by hayabusabusa** [secretused/MentaSecondTestApp#2]
## 📝 詳細

`ListAddedData` というシングルトンが作成されていますが、
シングルトンの場合イニシャライザを `private` にする必要があります。

シングルトンは**インスタンスが1個しか生成されないことを保証する**というものなので、  
現在のままでは `ListAddedData()` で新規のインスタンスを生成することができてしまいます。

```Swift
// NOTE: 現在の ListAddedData
class ListAddedData {
    static let shared = ListAddedData()
    
    // ...
}

// このように shared を無視してインスタンスが生成できる
let instance = ListAddedData()
```

イニシャライザを `private` にすることで上記のようにインスタンスが生成できなくなり、
シングルトンであることを明示できる + 実装上シングルトンであることが強制されるようになります。
個人的には `final` キーワードもつけて継承できないようにしても良いと思います。

```Swift
final class ListAddedData {
    static let shared = ListAddedData()

    // イニシャライザを private にする
    private init() { }
}

//let instance = ListAddedData() // こちらはエラーになり、shared からアクセスすることを強制できます
let instance = ListAddedData.shared
```

ちなみにですが、こちらのシングルトンはどのタイミングで使用するのでしょうか？
よろしければ教えてください🙇‍♂️

**Comment by yutaToba1008** [comment]
インスタンス生成の件了解しました。
TabbarでViewControllerとListViewControllerを分けています。
ViewControllerで映画検索してcellをタップ->RegisterViewControllerで映画情報確認、登録ボタンとなるのですが
登録ボタンをtapした時にListViewControllerのcellに登録したデータだけ追加sたいのですが、遷移はしたくなくNavigationControllerでの結びつきも持ちたくないのでSingletonを以前に勧められました。
自分的にはまだSingletonを上手く扱えずにいます。
ListViewControllerのCellに追加していくために使用するというのが正しいですかね？

**Comment by hayabusabusa** [comment]
なるほど！ViewController で表示した映画の情報を保存する場所としてシングルトンを使っている感じなんですね。
現状は特にデータの永続化等していないのでシングルトンでも問題ないかと思います。

**Comment by hayabusabusa** [comment]
@secretused 
こちらクローズしてしまいますね🙇‍♂️
