### ISSUE TITLE
main.storyboard に全ての ViewController が定義されていることについて

### ISSUE THREAD

**Issue by hayabusabusa** [secretused/MentaSecondTestApp#5]
## 📝 詳細

現在全ての ViewController が `main.storyboard` に定義されていますが、
もし今後アプリの画面数が大きくなってくると `main.storyboard` が重くなり、開発効率が落ちてしまいます。

現状のままでも何かエラーが出たり、不具合が生じるわけではありませんが、
個人的には ViewController と Storyboard は1対1になるような構成にするのがおすすめです。

これに関しては以前記事にしたことがあるので、よければ参考にしてみてください。

- [【Swift】プロジェクト作成時に生成されるMain.storyboardを削除する](https://qiita.com/hayabusabusa/items/f4852c89d6c35f5f0783)
- [【Swift】コードでViewControllerを生成して画面遷移と値渡しをする方法](https://qiita.com/hayabusabusa/items/13df207b51c307e57201)
- [iOS開発初心者だったあの頃の自分にアドバイスしたいこと UI編](https://note.com/hayabusabusa/n/nae9c3a579252)

**Comment by yutaToba1008** [comment]
以前から疑問に思っていました。
storyboardが複数？と思っていたのですが、分けることによって利点はなんですか？
また紐付けなどを一つのstoryboardでしていると思うのですが、紐付けができないとなるとコードで書くということですか？
あまりstoryboardが複数あるということがイメージしづらく、まずstoryboardとは何のか。も曖昧です。

**Comment by hayabusabusa** [comment]
@secretused 
> あまりstoryboardが複数あるということがイメージしづらく、まずstoryboardとは何のか。も曖昧です。

なるほど！それでは一点ずつ回答させていただきますね。

複数あるイメージがしづらいのもわかります。
[Storyboard が複数ある構成で作ったもの](https://github.com/hayabusabusa/MentaAutoLayoutEx)があるので、手元に落としてみてもらえば少しはヒントになるかもしれません。

## Storyboard とは

Storyboard は iOS 開発における画面を表す ViewController と、その画面レイアウトを GUI で作成できるものです。
昨今の iOS 開発でもメインで使われていて、画面のレイアウトを部品を置いて直感的に作ることができるのがメリットになります。

## Storyboard を分けるメリットについて

`main.storyboard` 一つで管理していると以下のようなデメリットがあります。

1. 画面が増えるごとに `main.storyboard` が重くなり、開発効率が落ちる
1. `main.storyboard` から ViewController を**コードで生成する**際に Storyboard ID が必要になり手間になる

これらのデメリットは ViewController と Storyboard が1対1になるように分けることで上記を解決することが出来ます。

1 については Storyboard を分けているので、Storyboard 1つ1つが軽くなるのはイメージしやすいと思います。

2 については現在 **performSegue** を使って画面遷移をしているためイメージしづらいかもしれないです。
画面遷移は **performSegue** でも実現できますが、そもそも **performSegue** 経由しないといけなかったり、値渡ししたいオブジェクトを `Any` として受け取ってしまうというデメリットがあります。

それに対して ViewController をコードから生成するようにすると、以下のコードのように遷移や値渡しがスムーズに行えます。
他にも **performSegue** を使っている場合は、一度 Storyboard を開かないと画面遷移の状態が確認できなかったりするので、
コードで ViewController を生成し、画面遷移を行ってしまうことが多いです。

```Swift
// performSegue で遷移の場合

// 引数 sender に渡したものが `Any` になってしまう
performSegue(withIdentifier: "registerControl", sender: items[indexPath.row])

override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
    // Segue の ID を確認、値渡ししたいものをキャストして確認とやることが多い
    if segue.identifier == "registerControl"{
        let nextVC: RegisterViewController = segue.destination as! RegisterViewController
        if let selecteditems = sender as? Item{
            nextVC.item = selecteditems
        }
}
        
// コードで画面遷移をする場合

// RegisterViewController.storyboard という Storyboard を作成した前提のコードになります.
// Storyboard から ViewController を生成
let nextVC = UIStoryboard(name: "RegisterViewController", bundle: nil).instantiateInitialViewController() as! RegisterViewController

// 渡したいものを生成した ViewController へ渡す.
nextVC.item = items[indexPath.row]

// 例えば NavigationController を使用して遷移する場合です.
navigationController?.pushViewController(nextVC, animated: true)
```

**Comment by yutaToba1008** [comment]
> コードで ViewController を生成し、画面遷移を行ってしまうことが多いです。

そうなのですね、自分も紐付けがどこになっているのかViewが増えると複雑になるのでこのやり方も
覚えていきたいと思います。

**Comment by hayabusabusa** [comment]
@secretused 
コードで遷移等を行った方が **performSegue** を使うより自由度が上がるので、オススメです。
参考になりそうな記事をいくつか上に載せているので、よかったら目を通してみてください。

**Comment by yutaToba1008** [comment]
分かりました。
ありがとうございます。

**Comment by hayabusabusa** [comment]
@secretused 
こちら他に質問事項等なさそうなのでクローズしてしまいますね🙇‍♂️
