### ISSUE TITLE
ビルドエラーについて

### ISSUE THREAD

**Issue by hayabusabusa** [secretused/MentaSecondTestApp#6]
## 📝 詳細

すみませんが、ビルドできない状態なのでいくつか確認させてください 🙇‍♂️

CocoaPods を使って Realm を導入されたようですが、
`Podfile` 及び `Podfile.lock` ファイルがないので、こちらで `pod install` することが出来ません。( xcworkspace もありませんが、自前で統合していると言うことでしょうか？ )
上記ファイルは CocoaPods を使ったプロジェクトでは必須なので、Git の管理外にしない方がいいと思います。

他にもソースコードが一部おかしかったりしてビルドができません。

```Swift
class ListViewController: UIViewController {
    
    var list:[RegisteredMovie]{
        
        switch segmentedControl.selectedSegmentIndex {
        case 0:
            // `ListAddedData` がコメントアウトされているのに存在している.
            return ListAddedData.shared.allList
        case 1:
            // `ListAddedData` がコメントアウトされているのに存在している.
            return ListAddedData.shared.selectedList
        default:
            fatalError("caseでカバーできません")
        }
    }

    // ...
}
```

申し訳ありませんが、一度ご確認をお願いいたします。

**Comment by yutaToba1008** [comment]
すみません。Podfile,Podfile.lockをcommitしていませんでした。
またソースコードの部分変更できていませんでしたが、そちらが先程MENTAの方で質問した箇所になります。

> xcworkspace もありませんが、自前で統合していると言うことでしょうか？

こちらの意味がよくわからないのですがxcworkspaceで必要なものはSourceTreeだと画像のうちどちらに当たりますか？
![スクリーンショット 2020-09-02 21 09 18](https://user-images.githubusercontent.com/67790604/91979205-61b33800-ed60-11ea-93d1-1954d28921bd.png)

**Comment by hayabusabusa** [comment]
@secretused 
> またソースコードの部分変更できていませんでしたが、そちらが先程MENTAの方で質問した箇所になります。

なるほど！
では `list` をセグメントの操作で分岐させている部分が現在つまっている箇所ということで大丈夫ですか？

> xcworkspaceで必要なものはSourceTreeだと画像のうちどちらに当たりますか？

通常 CocoaPods を利用したプロジェクトでは `pod install` を実行すると `xcworkspace` というファイルが作られるはずですが、そちらがなかったので質問させていただきました。
あげていただいた Source Tree の画像には `xcworkspace` がそもそも存在していないので、現状どういう状態なのかもう少し詳しく教えていただきたいです。

**Podfile** を作成し、`pod install` は実行されていますか？

**Comment by yutaToba1008** [comment]
> では list をセグメントの操作で分岐させている部分が現在つまっている箇所ということで大丈夫ですか？

はい！そうです。

> Podfile を作成し、pod install は実行されていますか？

はい,CocoaPodsとRealmSwiftをpod insatllしてxcworkspaceの方で作業しています。
そのためエラーなくRealmSwiftもインポートできています。
また,MentaSecondAppsのディレクトリにも含まれてます。
まだPodfileはCommitしていませんが、なぜxcworkspaceは存在していないのでしょうか？

**Comment by hayabusabusa** [comment]
@secretused 

> はい,CocoaPodsとRealmSwiftをpod insatllしてxcworkspaceの方で作業しています。
まだPodfileはCommitしていませんが、なぜxcworkspaceは存在していないのでしょうか？

すみません、上記2文が矛盾していて状況が把握できていないのですが、
もしかして現在 Github のこちらのリポジトリにアップされているプロジェクトとは別のプロジェクトがあって、
そちらでも作業されているということですか？

**Comment by yutaToba1008** [comment]
白色のプロジェクトファイル(xcworkspace)で作業をしています。
Github のこちらのリポジトリにアップした時は青色のプロジェクトファイルでした。
それからRealm導入のためPodFileを作成したのでまだGithubにはPodFile後のものはアップされていません。
その場合 **別のプロジェクト**　で作業しているという認識になりますか？

青色のプロジェクトファイルから白色のプロジェクトファイルに替えた際に(Commit message:Realm導入&一部可読化)
自然とSourceTreeで白色のプロジェクトファイルもCommitされてGithubに反映されるのだとばかり思っていました。

**Comment by hayabusabusa** [comment]
@secretused 
あ、いえ。
`xcodeproj` (青いプロジェクトファイル)か `xcworkspace` (白いプロジェクトファイル)かどうか
ということではなく、そもそもこちらの **MentaSecondTestApp** リポジトリにアップして Git で管理しているプロジェクトとは別で、他の Git にアップしていないプロジェクトで作業されているかどうかという意味でした🙇‍♂️

> 青色のプロジェクトファイルから白色のプロジェクトファイルに替えた際に(Commit message:Realm導入&一部可読化)
自然とSourceTreeで白色のプロジェクトファイルもCommitされてGithubに反映されるのだとばかり思っていました。

はい、普通はそうなると思います。
特に `xcworkspace` が gitignore に指定されているということもないので... 🤔

ちなみに `xcworkspace` は CocoaPods でインストールしたライブラリと `xcodeproj` をリンクしてまとめるために使用されているため、プロジェクトが2つに別れてしまうということはありません。

試しに手元で `pod init` で `Podfile` を生成して、**RealmSwift** をインストールしてみました。
ファイルの構成は私のものと同じようになっているか確認してもらえませんか？
**Sample** という名前でプロジェクトを作成しました。

| ファイル構成の画像 |
| :------------------: |
| <img width="412" alt="スクリーンショット 2020-09-03 0 52 18" src="https://user-images.githubusercontent.com/31949692/92006540-d3e74500-ed7f-11ea-9c0a-4830cbf5841d.png"> |

**Comment by yutaToba1008** [comment]
画像添付します。ご確認よろしくお願いします。
![スクリーンショット 2020-09-03 1 13 35](https://user-images.githubusercontent.com/67790604/92008794-8fa97400-ed82-11ea-8a04-5b13581c92c5.png)

**Comment by hayabusabusa** [comment]
@secretused 
問題なさそうですね...🤔
それでは一度プッシュしてもらってもいいですか？

**Comment by yutaToba1008** [comment]
何かを選択してコミットせずにそのままプッシュすれば良いですか？

**Comment by hayabusabusa** [comment]
@secretused 
今って Github の **master** ブランチは最新の状態で、
ローカルからプッシュしていない変更等はない状態でしょうか？

**Comment by yutaToba1008** [comment]
ListViewControllerをViewWillAppearの関係で変更はしました。
Mが付いているのはそれのみです。(ローカルからプッシュしていない変更がそれに該当するのかはわかりませんが)

**Comment by hayabusabusa** [comment]
@secretused 
もしかしたら、Git の履歴が上手く反映できていないのかもしれないですね🤔

今って Source Tree はどのようになっていますか？
こちらのリポジトリをクローンしていますが、**Realm導入&一部可読化**、**addListTapped**というコミットが反映されていて、どちらにも CocoaPods に関するファイルは追加されていない状態になっています。

<img width="726" alt="スクリーンショット 2020-09-03 10 29 57" src="https://user-images.githubusercontent.com/31949692/92061315-e473db80-edd0-11ea-8edc-e80b66d13e12.png">

**Comment by yutaToba1008** [comment]
現在の状態です。ご確認よろしくお願いします。
![スクリーンショット 2020-09-03 10 53 19](https://user-images.githubusercontent.com/67790604/92062380-93191b80-edd3-11ea-8569-5ce4ab186994.png)

**Comment by hayabusabusa** [comment]
@secretused 
CocoaPods 関連のファイル生成されていますね... 😅
変更が `462` と大量にあってちょっと気になるかもしれませんが、全てのファイルをステージングに移動させてコミット、プッシュしてもらってもいいですか？
( 本来は gitignore に `Pods` ディレクトリ以下は Git の管理外になるように記述するべきですが、時短のために省略します。 )

![92062380-93191b80-edd3-11ea-8569-5ce4ab186994](https://user-images.githubusercontent.com/31949692/92062735-5f8ac100-edd4-11ea-89ac-42b7843e3f20.png)

**Comment by yutaToba1008** [comment]
462個全て選択してコミットするでよろしいのですか？

**Comment by hayabusabusa** [comment]
@secretused 
はい、そうです。
もし変更が多すぎるのが気になる場合は gitignore の以下のコメントアウトを外していただければ、
変更の数がだいぶ少なくなると思います。

```
# CocoaPods
#
# We recommend against adding the Pods directory to your .gitignore. However
# you should judge for yourself, the pros and cons are mentioned at:
# https://guides.cocoapods.org/using/using-cocoapods.html#should-i-check-the-pods-directory-into-source-control
#
Pods/ # コメントアウトを外す
#
# Add this line if you want to avoid checking in source code from the Xcode workspace
# *.xcworkspace
```

**Comment by yutaToba1008** [comment]
gitignoreでPodsを管理外にしてから変更しました。
ご確認よろしくお願いします。

**Comment by hayabusabusa** [comment]
@secretused 
ありがとうございます！完璧です👍

**Comment by yutaToba1008** [comment]
そうですか！良かったです😌
では昨日分からなかったSegmentedControll及びRealm動作(ListViewControllerのViewWillAppearをまだCommitしていません)の
ご確認よろしくお願いします。

また質問なのですが、実務ではどの程度/頻度でCommitしているのでしょうか？

**Comment by hayabusabusa** [comment]
@secretused 
承知しました🙇‍♂️
そちらに関してはこの issue のスレッドが長くなってしまったので、別の issue を立ててアドバイスさせていただきますね。

> また質問なのですが、実務ではどの程度/頻度でCommitしているのでしょうか？

コミットは細かい程度、頻度で行い、機能単位でプルリクエストをします。

例えば、API のレスポンスを表すモデルオブジェクトを追加、定義までしてコミット、
複数ファイルに影響が及ぶ実装だった場合は動作する最低限まで実装してコミットするイメージです。
コミットメッセージも何を変更したのかわかりやすくすることでレビューワーにも変更をわかりやすく伝えることができます。

**Comment by yutaToba1008** [comment]
issueの件了解です。

そうなのですね !ありがとうございます。
自分からはこのIssueでは以上となります。
