### ISSUE TITLE
ListViewController の DataSource 切り替えについて

### ISSUE THREAD

**Issue by hayabusabusa** [secretused/MentaSecondTestApp#7]
## 📝 詳細

質問させていただきたいのですが、
`allList` と `selectedList` にはどのような違いがあるのでしょうか？
 `selectedList` は TODO で言うすでに実行済みのタスクのようなものなのでしょうか？

あと `メソッドsegmentSelcted同等の処理なら不要` というコメントで `viewWillAppear()` がコメントアウトされていますが、
現状のままだと以下の操作を行った場合リストが更新されません。

- **ViewController** からデータを選択して **RegisterViewController** に遷移
- **RegisterViewController** でデータを Realm へ登録
- **ViewController** へ戻って、タブを **ListViewController** へ切り替える
- `viewDidLoad()` でのみ更新されているため Realm に登録したデータが **ListViewController** に表示されていない

なので、`viewWillAppear()` はコメントアウトせずに、
Realm のデータを読み込む処理を `viewWillAppear()` で行う必要があります。

**Comment by yutaToba1008** [comment]
> selectedList は TODO で言うすでに実行済みのタスクのようなものなのでしょうか？

はい、そうなります。allListのSwipeActionsConfigurationForRowAt移動させる形となります。

コメントアウトの件はUISegmentedControlでもreloadData()しているのでSegmentedControllを切り替えるたびに
reloadData()しているののならば、viewWillAppear()と同等かな？と思ったのですが
SegmentedControllのreloadData()も教えてもらったやり方なので何をしているのかあまり理解できていません。
なのでコメントで一応書いておきました。

> viewWillAppear() はコメントアウトせずに、
Realm のデータを読み込む処理を viewWillAppear() で行う必要があります。

今ViewDidLoadで行っている
`let realm = try! Realm()
        movieItems = realm.objects(RegisteredMovie.self)`
をviewWillAppearで行った方が良いということですか？

**Comment by hayabusabusa** [comment]
@secretused 

> 今ViewDidLoadで行っている
let realm = try! Realm() movieItems = realm.objects(RegisteredMovie.self)
をviewWillAppearで行った方が良いということですか？

はい。まさしくその通りです！

> UISegmentedControlでもreloadData()しているのでSegmentedControllを切り替えるたびに
reloadData()しているののならば、viewWillAppear()と同等かな？と思ったのですが

いえ少し動作が違います。というかそもそも両者とも目的が違いますね。
`UISegmentedControl` の方はデータの**切り替え**を行うために使用されていて、
`viewWillAppear()` はデータを**更新**するために使用されているイメージになると思います。

**Comment by yutaToba1008** [comment]
`データの切り替え`とはどういうことですか？

**Comment by hayabusabusa** [comment]
@secretused 
`selectedList` は TODO で言うすでに実行済みのタスクのようなものだということなので、
選択した全てのデータ `allList` とすでに試聴済み(?)のデータ `selectedList` を `tableView.reloadData()` で切り替えるという意味です。
動作としてはあっていると思いますが、間違っていますか？

**Comment by yutaToba1008** [comment]
そういう事ですか、分かりました！
理解が乏しくてすみません。

**Comment by hayabusabusa** [comment]
@secretused 
こちらこそ紛らわしい説明になって申し訳ありませんでした🙇‍♂️
私から質問させていただきたいことは以上になるので、他に質問事項等なければクローズしてしまいますね。

**Comment by yutaToba1008** [comment]
クローズでお願いします。
